##############################################################
#######              CONNEXION/INSCRIPTION             #######
##############################################################

### GET Connexion
GET http://localhost:10000/connexion?email=cyndie@gmail.com&password=cyndie

### POST Inscription
POST http://localhost:10000/inscription
Content-Type: application/json

{
  "nom": "Poppé",
  "prenom": "Christophe",
  "email": "christophe@gmail.com",
  "password": "christophe",
  "id_puce": 2,
  "id_type": 1,
  "id_classe": null
}

##############################################################
#######                      USERS                     #######
##############################################################

### GET Tous les utilisateurs
GET http://localhost:10000/users

### GET Détails d'un utilisateur
GET http://localhost:10000/users/1

### PUT Modification d'un utilisateur
PUT http://localhost:10000/users/2
Content-Type: application/json

{
  "nom": "Bernezet",
  "prenom": "Julien",
  "email": "julien@gmail.com",
  "password": "julien",
  "id_puce": 2,
  "id_type": 2,
  "id_classe": 1
}

### DELETE Suppression d'un utilisateur
DELETE http://localhost:10000/users/3

### GET Liste utilisateurs selon le type
GET http://localhost:10000/users/type/2

##############################################################
#######                      TYPES                     #######
##############################################################

### GET Tous les utilisateurs
GET http://localhost:10000/types

### GET Info d'un utilisateur
GET http://localhost:10000/types/1

### POST Création d'un type
POST http://localhost:10000/types
Content-Type: application/json

{
  "nom": "Prof"
}

### PUT Modification d'un type
PUT http://localhost:10000/types/1
Content-Type: application/json

{
  "nom": "Admin"
}

### DELETE Suppression d'un type
DELETE http://localhost:10000/types/2


##############################################################
#######                     CLASSES                    #######
##############################################################

### GET Toutes les classes
GET http://localhost:10000/classes

### POST Création d'une classe
POST http://localhost:10000/classes
Content-Type: application/json

{
  "nom": "19-20_CSIA",
  "effectif": 32
}

### GET Info d'une classe
GET http://localhost:10000/classes/2

### PUT Modification d'une classe
PUT http://localhost:10000/classes/2
Content-Type: application/json

{
  "nom": "1920_CSIA",
  "effectif": 33
}

### DELETE Suppression d'une classe
DELETE http://localhost:10000/classes/2

### GET Liste des élèves d'une classe
GET http://localhost:10000/classes/users/1

##############################################################
#######                     SALLES                     #######
##############################################################

### GET Toutes les salles
GET http://localhost:10000/salles

### POST Création d'une classe
POST http://localhost:10000/salles
Content-Type: application/json

{
  "numero_salle": "205",
  "etage": 0,
  "type": "Informatique",
  "occupee": 0,
  "capacite": 25
}

### GET Info d'une salles
GET http://localhost:10000/salles/2

### PUT Modification d'une salles
PUT http://localhost:10000/salles/2
Content-Type: application/json

{
  "numero_salle": "205",
  "etage": 0,
  "type": "Informatique",
  "occupee": 0,
  "capacite": 20
}

### DELETE Suppression d'une salle
DELETE http://localhost:10000/salles/2


### GET Liste des portes d'une salle
GET http://localhost:10000/salles/portes/1

##############################################################
#######                     PORTES                     #######
##############################################################

### GET Toutes les portes
GET http://localhost:10000/portes

### POST Création d'une porte
POST http://localhost:10000/portes
Content-Type: application/json

{
  "numero_porte": 15,
  "id_salle": 1
}

### GET Info d'une porte
GET http://localhost:10000/portes/3

### PUT Modification d'une porte
PUT http://localhost:10000/portes/3
Content-Type: application/json

{
  "numero_porte": 3,
  "id_salle": 1
}

### DELETE Suppression d'une porte
DELETE http://localhost:10000/portes/3

##############################################################
#######                   RESERVATION                  #######
##############################################################

### GET Toutes les réservations
GET http://localhost:10000/reservations

### POST Création d'une réservation
POST http://localhost:10000/reservations
Content-Type: application/json

{
  "id_user": 2,
  "date": "2019-01-21",
  "heure_debut": "09:00",
  "heure_fin": "10:00",
  "intitule": "Récré",
  "nb_personnes": 2,
  "id_salle": 1,
  "id_prof": 1
}

### GET Info d'une réservation
GET http://localhost:10000/reservations/1

### PUT Modification d'une réservation
PUT http://localhost:10000/reservations/2
Content-Type: application/json

{
  "heure_fin": "17:10:00",
  "intitule": "Conv entre meufs",
  "nb_personnes": 3
}

### DELETE Suppression d'une réservation
DELETE http://localhost:10000/reservations/2


### GET Réservations non validées
GET http://localhost:10000/reservations/attente

### POST Validation réservation
POST http://localhost:10000/reservations/validation/2
Content-Type: application/json

{
  "etat": 0,
  "id_user": 2
}

### GET All validations
GET http://localhost:10000/validations

### GET Info d'une validation
GET http://localhost:10000/validations/17

### PUT Modification d'une validation
PUT http://localhost:10000/validations/17
Content-Type: application/json

{
  "etat": 0
}

### DELETE Suppression d'une validation
DELETE http://localhost:10000/validations/2

### GET Validations by user
GET http://localhost:10000/validations/user/1

### GET Validations by status

GET http://localhost:10000/validations/status/1

### GET Accès aux salles selon validation
# Tests locaux
# Etudiant : 121235489
# Prof : 23
# Admin : 2687A000
GET http://localhost:10000/acces/1/121235489

### GET Salles dispo actuellement
GET http://localhost:10000/salles/dispoNow

### GET Salles réservées à telle date
GET http://localhost:10000/salles/reservees/2020-08-21

###
